.PHONY: ALL  QQ_01 QQ_02 JD TAOBAO ALIPAY PHONE PHONE_ZHUOFEI MAIL_126 MAIL_QQ_01 MAIL_QQ_02 JUNIOR_SCHOOL BIRTH_PLACE APPLE GITHUB APS POCKET
.PHONY: READABILITY_01 READABILITY_02 BAIDU_01 BAIDU_02 PLEX MSN MATLAB TPOOO DOUBAN

ALL: QQ_01 QQ_02 JD TAOBAO ALIPAY APPLE GITHUB APS POCKET READABILITY_01 READABILITY_02 BAIDU_01 BAIDU_02 PLEX MSN MATLAB TPOOO DOUBAN
	@echo '----------------------------------------------------------------'
	@echo that is all

MSN:
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo lijianchao5012@hotmail.com
 
MAIL_QQ_01:
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012@foxmail.com
 
MAIL_QQ_02:
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 1053039124@qq.com 
MAIL_126:
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo lijianchao5555@126.com 

PHONE_ZHUOFEI:
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 13434779537 

PHONE: 
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 13242095131
 
JUNIOR_SCHOOL: 
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo liuchunling 

BIRTH_PLACE: 
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo shanxixingping 

QQ_01: PHONE PHONE_ZHUOFEI
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 475801401
 

QQ_02: JUNIOR_SCHOOL BIRTH_PLACE
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 1053019124 

JD: PHONE MAIL_126
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo suisuibianbianzhuanzhuan
	
TAOBAO: PHONE MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012


ALIPAY: PHONE MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012@foxmail.com


APPLE:  MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 475801401@qq.com

GITHUB: MAIL_126
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
APS: MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 

POCKET: MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 

READABILITY_01:  MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
READABILITY_02:  MAIL_QQ_02
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5013 

BAIDU_01:  MAIL_126
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
BAIDU_02:  MAIL_QQ_02
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5013

PLEX:  MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012
MATLAB:  MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo 475801401@qq.com
DOUBAN:  MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
TPOOO: MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
DOUBAN: MAIL_QQ_01
	@echo '----------------------------------------------------------------'
	@echo $@:pre:$+
	@echo feman5012 
